# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20160327_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='published',
            new_name='is_published',
        ),
    ]
