# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_topic_name'),
        ('questions', '0011_auto_20160327_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='topics.Topic'),
            preserve_default=False,
        ),
    ]
