# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-20 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_topic_name'),
        ('questions', '0014_question_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(related_name='questions', to='topics.Topic'),
        ),
    ]
