# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
    ]
