# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_remove_topic_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '\u0422\u043e\u043f\u0438\u043a', 'verbose_name_plural': '\u0422\u043e\u043f\u0438\u043a\u0438'},
        ),
    ]
