# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_topic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
    ]
